# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- script: npm i $(Agent.BuildDirectory)\s\R2.ML.DeepLearning\ClientApp
- script: ng build --prod $(Agent.BuildDirectory)\s\R2.ML.DeepLearning\ClientApp
- script: dotnet restore $(Agent.BuildDirectory)\s\R2.ML.DeepLearning\R2.ML.DeepLearning.csproj
- script: dotnet build $(Agent.BuildDirectory)\s\R2.ML.DeepLearning\R2.ML.DeepLearning.csproj --configuration $(buildConfiguration)

