import {
  Injectable
} from '@angular/core';
import {
  Observable,
  of
} from 'rxjs';
import { ProductList } from '../../states/products/products.interface';

@Injectable()
export class ProductListService {
  constructor() {}

  getProducts(): Observable <ProductList> {
    const data = {
      'data': [{
        'Id': 15,
        'PictureThumbnailUrl': '//demo.smartstore.com/backend/media/image/55/apple-iphone-6.jpg?size=250',
        'NoThumb': false,
        'ProductTypeId': 0,
        'ProductTypeName': '',
        'ProductTypeLabelHint': 'secondary d-none',
        'ProductUrl': null,
        'AssociatedToProductId': 0,
        'AssociatedToProductName': null,
        'VisibleIndividually': false,
        'ProductTemplateId': 0,
        'AvailableProductTemplates': [],
        'Name': 'Apple iPhone 6',
        'ShortDescription': null,
        'FullDescription': null,
        'AdminComment': null,
        'ShowOnHomePage': false,
        'HomePageDisplayOrder': 0,
        'MetaKeywords': null,
        'MetaDescription': null,
        'MetaTitle': null,
        'SeName': null,
        'AllowCustomerReviews': false,
        'ProductTags': null,
        'AvailableProductTags': null,
        'Sku': 'Apple-1001',
        'ManufacturerPartNumber': null,
        'Gtin': null,
        'CustomsTariffNumber': null,
        'CountryOfOriginId': null,
        'AvailableCountries': [],
        'IsGiftCard': false,
        'GiftCardTypeId': 0,
        'RequireOtherProducts': false,
        'RequiredProductIds': null,
        'AutomaticallyAddRequiredProducts': false,
        'IsDownload': false,
        'DownloadId': null,
        'UnlimitedDownloads': false,
        'MaxNumberOfDownloads': 0,
        'DownloadExpirationDays': null,
        'DownloadActivationTypeId': 0,
        'HasSampleDownload': false,
        'SampleDownloadId': null,
        'HasUserAgreement': false,
        'UserAgreementText': null,
        'IsRecurring': false,
        'RecurringCycleLength': 0,
        'RecurringCyclePeriodId': 0,
        'RecurringTotalCycles': 0,
        'IsShipEnabled': false,
        'IsFreeShipping': false,
        'AdditionalShippingCharge': 0.0,
        'IsEsd': false,
        'IsTaxExempt': false,
        'TaxCategoryId': 0,
        'AvailableTaxCategories': [],
        'ManageInventoryMethodId': 0,
        'AvailableManageInventoryMethods': [],
        'StockQuantity': 10000,
        'DisplayStockAvailability': false,
        'DisplayStockQuantity': false,
        'MinStockQuantity': 0,
        'LowStockActivityId': 0,
        'NotifyAdminForQuantityBelow': 0,
        'BackorderModeId': 0,
        'AllowBackInStockSubscriptions': false,
        'OrderMinimumQuantity': 0,
        'OrderMaximumQuantity': 0,
        'QuantityStep': 0,
        'QuantiyControlType': 0,
        'HideQuantityControl': false,
        'AllowedQuantities': null,
        'DisableBuyButton': false,
        'DisableWishlistButton': false,
        'AvailableForPreOrder': false,
        'CallForPrice': false,
        'Price': 579.0000,
        'OldPrice': 0.0,
        'ProductCost': 0.0,
        'SpecialPrice': null,
        'SpecialPriceStartDateTimeUtc': null,
        'SpecialPriceEndDateTimeUtc': null,
        'CustomerEntersPrice': false,
        'MinimumCustomerEnteredPrice': 0.0,
        'MaximumCustomerEnteredPrice': 0.0,
        'Weight': 0.0,
        'Length': 0.0,
        'Width': 0.0,
        'Height': 0.0,
        'AvailableStartDateTimeUtc': null,
        'AvailableEndDateTimeUtc': null,
        'Published': false,
        'CreatedOn': 'Date(1482154757467+0100)',
        'UpdatedOn': 'Date(1482943161917+0100)',
        'BundleTitleText': null,
        'BundlePerItemPricing': false,
        'BundlePerItemShipping': false,
        'BundlePerItemShoppingCart': false,
        'PrimaryStoreCurrencyCode': null,
        'BaseDimensionIn': null,
        'BaseWeightIn': null,
        'Locales': [],
        'SubjectToAcl': false,
        'AvailableCustomerRoles': null,
        'SelectedCustomerRoleIds': null,
        'LimitedToStores': false,
        'AvailableStores': null,
        'SelectedStoreIds': null,
        'NumberOfAvailableCategories': 0,
        'NumberOfAvailableManufacturers': 0,
        'NumberOfAvailableProductAttributes': 0,
        'AddPictureModel': {

          'ProductId': 0,
          'PictureId': 0,
          'PictureUrl': null,
          'DisplayOrder': 0,
          'Id': 0,
          'CustomProperties': {

          }
        },
        'ProductPictureModels': [],
        'AvailableDiscounts': null,
        'SelectedDiscountIds': null,
        'AddSpecificationAttributeModel': {
          'SpecificationAttributeId': 0,
          'SpecificationAttributeOptionId': 0,
          'AllowFiltering': null,
          'ShowOnProductPage': null,
          'DisplayOrder': 0,
          'AvailableAttributes': [],
          'AvailableOptions': [],
          'CustomProperties': {

          }
        },
        'CopyProductModel': {

          'NumberOfCopies': 1,
          'Name': null,
          'CopyImages': false,
          'Published': false,
          'Id': 0,
          'CustomProperties': {

          }
        },
        'BasePriceEnabled': false,
        'BasePriceMeasureUnit': null,
        'BasePriceAmount': null,
        'BasePriceBaseAmount': null,
        'AvailableMeasureWeights': [],
        'AvailableMeasureUnits': [],
        'DeliveryTimeId': null,
        'AvailableDeliveryTimes': [],
        'QuantityUnitId': null,
        'AvailableQuantityUnits': [],
        'ProductSelectCheckboxClass': null,
        'IsSystemProduct': false,
        'SystemName': null,
        'LoadedTabs': null,
        'CustomProperties': {
        }
      }, {

        'Id': 260,
        'PictureThumbnailUrl': '//demo.smartstore.com/backend/media/image/3009/iphone-plus.jpg?size=250',
        'NoThumb': false,
        'ProductTypeId': 0,
        'ProductTypeName': '',
        'ProductTypeLabelHint': 'secondary d-none',
        'ProductUrl': null,
        'AssociatedToProductId': 0,
        'AssociatedToProductName': null,
        'VisibleIndividually': false,
        'ProductTemplateId': 0,
        'AvailableProductTemplates': [],
        'Name': 'iPhone Plus',
        'ShortDescription': null,
        'FullDescription': null,
        'AdminComment': null,
        'ShowOnHomePage': false,
        'HomePageDisplayOrder': 0,
        'MetaKeywords': null,
        'MetaDescription': null,
        'MetaTitle': null,
        'SeName': null,
        'AllowCustomerReviews': false,
        'ProductTags': null,
        'AvailableProductTags': null,
        'Sku': null,
        'ManufacturerPartNumber': null,
        'Gtin': null,
        'CustomsTariffNumber': null,
        'CountryOfOriginId': null,
        'AvailableCountries': [],
        'IsGiftCard': false,
        'GiftCardTypeId': 0,
        'RequireOtherProducts': false,
        'RequiredProductIds': null,
        'AutomaticallyAddRequiredProducts': false,
        'IsDownload': false,
        'DownloadId': null,
        'UnlimitedDownloads': false,
        'MaxNumberOfDownloads': 0,
        'DownloadExpirationDays': null,
        'DownloadActivationTypeId': 0,
        'HasSampleDownload': false,
        'SampleDownloadId': null,
        'HasUserAgreement': false,
        'UserAgreementText': null,
        'IsRecurring': false,
        'RecurringCycleLength': 0,
        'RecurringCyclePeriodId': 0,
        'RecurringTotalCycles': 0,
        'IsShipEnabled': false,
        'IsFreeShipping': false,
        'AdditionalShippingCharge': 0.0,
        'IsEsd': false,
        'IsTaxExempt': false,
        'TaxCategoryId': 0,
        'AvailableTaxCategories': [],
        'ManageInventoryMethodId': 0,
        'AvailableManageInventoryMethods': [],
        'StockQuantity': 10000,
        'DisplayStockAvailability': false,
        'DisplayStockQuantity': false,
        'MinStockQuantity': 0,
        'LowStockActivityId': 0,
        'NotifyAdminForQuantityBelow': 0,
        'BackorderModeId': 0,
        'AllowBackInStockSubscriptions': false,
        'OrderMinimumQuantity': 0,
        'OrderMaximumQuantity': 0,
        'QuantityStep': 0,
        'QuantiyControlType': 0,
        'HideQuantityControl': false,
        'AllowedQuantities': null,
        'DisableBuyButton': false,
        'DisableWishlistButton': false,
        'AvailableForPreOrder': false,
        'CallForPrice': false,
        'Price': 799.0000,
        'OldPrice': 0.0,
        'ProductCost': 0.0,
        'SpecialPrice': null,
        'SpecialPriceStartDateTimeUtc': null,
        'SpecialPriceEndDateTimeUtc': null,
        'CustomerEntersPrice': false,
        'MinimumCustomerEnteredPrice': 0.0,
        'MaximumCustomerEnteredPrice': 0.0,
        'Weight': 0.0,
        'Length': 0.0,
        'Width': 0.0,
        'Height': 0.0,
        'AvailableStartDateTimeUtc': null,
        'AvailableEndDateTimeUtc': null,
        'Published': true,
        'CreatedOn': 'Date(1490281179903+0100)',
        'UpdatedOn': 'Date(1493902948493+0200)',
        'BundleTitleText': null,
        'BundlePerItemPricing': false,
        'BundlePerItemShipping': false,
        'BundlePerItemShoppingCart': false,
        'PrimaryStoreCurrencyCode': null,
        'BaseDimensionIn': null,
        'BaseWeightIn': null,
        'Locales': [],
        'SubjectToAcl': false,
        'AvailableCustomerRoles': null,
        'SelectedCustomerRoleIds': null,
        'LimitedToStores': false,
        'AvailableStores': null,
        'SelectedStoreIds': null,
        'NumberOfAvailableCategories': 0,
        'NumberOfAvailableManufacturers': 0,
        'NumberOfAvailableProductAttributes': 0,
        'AddPictureModel': {

          'ProductId': 0,
          'PictureId': 0,
          'PictureUrl': null,
          'DisplayOrder': 0,
          'Id': 0,
          'CustomProperties': {

          }
        },
        'ProductPictureModels': [],
        'AvailableDiscounts': null,
        'SelectedDiscountIds': null,
        'AddSpecificationAttributeModel': {
          'SpecificationAttributeId': 0,
          'SpecificationAttributeOptionId': 0,
          'AllowFiltering': null,
          'ShowOnProductPage': null,
          'DisplayOrder': 0,
          'AvailableAttributes': [],
          'AvailableOptions': [],
          'CustomProperties': {

          }
        },
        'CopyProductModel': {

          'NumberOfCopies': 1,
          'Name': null,
          'CopyImages': false,
          'Published': false,
          'Id': 0,
          'CustomProperties': {

          }
        },
        'BasePriceEnabled': false,
        'BasePriceMeasureUnit': null,
        'BasePriceAmount': null,
        'BasePriceBaseAmount': null,
        'AvailableMeasureWeights': [],
        'AvailableMeasureUnits': [],
        'DeliveryTimeId': null,
        'AvailableDeliveryTimes': [],
        'QuantityUnitId': null,
        'AvailableQuantityUnits': [],
        'ProductSelectCheckboxClass': null,
        'IsSystemProduct': false,
        'SystemName': null,
        'LoadedTabs': null,
        'CustomProperties': {
        }
      }, {

        'Id': 271,
        'PictureThumbnailUrl': '//demo.smartstore.com/backend/media/image/3045/iphone-plus-abo.jpg?size=250',
        'NoThumb': false,
        'ProductTypeId': 0,
        'ProductTypeName': '',
        'ProductTypeLabelHint': 'secondary d-none',
        'ProductUrl': null,
        'AssociatedToProductId': 0,
        'AssociatedToProductName': null,
        'VisibleIndividually': false,
        'ProductTemplateId': 0,
        'AvailableProductTemplates': [],
        'Name': 'iPhone Plus Abo',
        'ShortDescription': null,
        'FullDescription': null,
        'AdminComment': null,
        'ShowOnHomePage': false,
        'HomePageDisplayOrder': 0,
        'MetaKeywords': null,
        'MetaDescription': null,
        'MetaTitle': null,
        'SeName': null,
        'AllowCustomerReviews': false,
        'ProductTags': null,
        'AvailableProductTags': null,
        'Sku': null,
        'ManufacturerPartNumber': null,
        'Gtin': null,
        'CustomsTariffNumber': null,
        'CountryOfOriginId': null,
        'AvailableCountries': [],
        'IsGiftCard': false,
        'GiftCardTypeId': 0,
        'RequireOtherProducts': false,
        'RequiredProductIds': null,
        'AutomaticallyAddRequiredProducts': false,
        'IsDownload': false,
        'DownloadId': null,
        'UnlimitedDownloads': false,
        'MaxNumberOfDownloads': 0,
        'DownloadExpirationDays': null,
        'DownloadActivationTypeId': 0,
        'HasSampleDownload': false,
        'SampleDownloadId': null,
        'HasUserAgreement': false,
        'UserAgreementText': null,
        'IsRecurring': false,
        'RecurringCycleLength': 0,
        'RecurringCyclePeriodId': 0,
        'RecurringTotalCycles': 0,
        'IsShipEnabled': false,
        'IsFreeShipping': false,
        'AdditionalShippingCharge': 0.0,
        'IsEsd': false,
        'IsTaxExempt': false,
        'TaxCategoryId': 0,
        'AvailableTaxCategories': [],
        'ManageInventoryMethodId': 0,
        'AvailableManageInventoryMethods': [],
        'StockQuantity': 10000,
        'DisplayStockAvailability': false,
        'DisplayStockQuantity': false,
        'MinStockQuantity': 0,
        'LowStockActivityId': 0,
        'NotifyAdminForQuantityBelow': 0,
        'BackorderModeId': 0,
        'AllowBackInStockSubscriptions': false,
        'OrderMinimumQuantity': 0,
        'OrderMaximumQuantity': 0,
        'QuantityStep': 0,
        'QuantiyControlType': 0,
        'HideQuantityControl': false,
        'AllowedQuantities': null,
        'DisableBuyButton': false,
        'DisableWishlistButton': false,
        'AvailableForPreOrder': false,
        'CallForPrice': false,
        'Price': 799.0000,
        'OldPrice': 0.0,
        'ProductCost': 0.0,
        'SpecialPrice': null,
        'SpecialPriceStartDateTimeUtc': null,
        'SpecialPriceEndDateTimeUtc': null,
        'CustomerEntersPrice': false,
        'MinimumCustomerEnteredPrice': 0.0,
        'MaximumCustomerEnteredPrice': 0.0,
        'Weight': 0.0,
        'Length': 0.0,
        'Width': 0.0,
        'Height': 0.0,
        'AvailableStartDateTimeUtc': null,
        'AvailableEndDateTimeUtc': null,
        'Published': true,
        'CreatedOn': 'Date(1490628547887+0200)',
        'UpdatedOn': 'Date(1490629159303+0200)',
        'BundleTitleText': null,
        'BundlePerItemPricing': false,
        'BundlePerItemShipping': false,
        'BundlePerItemShoppingCart': false,
        'PrimaryStoreCurrencyCode': null,
        'BaseDimensionIn': null,
        'BaseWeightIn': null,
        'Locales': [],
        'SubjectToAcl': false,
        'AvailableCustomerRoles': null,
        'SelectedCustomerRoleIds': null,
        'LimitedToStores': false,
        'AvailableStores': null,
        'SelectedStoreIds': null,
        'NumberOfAvailableCategories': 0,
        'NumberOfAvailableManufacturers': 0,
        'NumberOfAvailableProductAttributes': 0,
        'AddPictureModel': {

          'ProductId': 0,
          'PictureId': 0,
          'PictureUrl': null,
          'DisplayOrder': 0,
          'Id': 0,
          'CustomProperties': {

          }
        },
        'ProductPictureModels': [],
        'AvailableDiscounts': null,
        'SelectedDiscountIds': null,
        'AddSpecificationAttributeModel': {
          'SpecificationAttributeId': 0,
          'SpecificationAttributeOptionId': 0,
          'AllowFiltering': null,
          'ShowOnProductPage': null,
          'DisplayOrder': 0,
          'AvailableAttributes': [],
          'AvailableOptions': [],
          'CustomProperties': {

          }
        },
        'CopyProductModel': {

          'NumberOfCopies': 1,
          'Name': null,
          'CopyImages': false,
          'Published': false,
          'Id': 0,
          'CustomProperties': {

          }
        },
        'BasePriceEnabled': false,
        'BasePriceMeasureUnit': null,
        'BasePriceAmount': null,
        'BasePriceBaseAmount': null,
        'AvailableMeasureWeights': [],
        'AvailableMeasureUnits': [],
        'DeliveryTimeId': null,
        'AvailableDeliveryTimes': [],
        'QuantityUnitId': null,
        'AvailableQuantityUnits': [],
        'ProductSelectCheckboxClass': null,
        'IsSystemProduct': false,
        'SystemName': null,
        'LoadedTabs': null,
        'CustomProperties': {
        }
      }],
      'total': 3
    };
    return of(data);
  }
}
